name: Build, Push, and Deploy Backend to AWS EC2

on:
  push:
    branches: [main]
    paths:
      - "api/**"
      - "model/**"
      - "color_changer/**"
      - "Dockerfile"
      - "requirements.txt"
      - ".github/workflows/deploy-backend.yml"
  pull_request:
    branches: [main]
    paths:
      - "api/**"
      - "model/**"
      - "color_changer/**"
      - "Dockerfile"
      - "requirements.txt"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/luviraai-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/luviraai-api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Get GitHub Actions Runner IP
        id: ip
        uses: haythem/public-ip@v1.3

      - name: Add Runner IP to AWS Security Group
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id 'sg-07be80aeabae4bf35' \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32 \
            --region ${{ secrets.AWS_REGION }}

      - name: Deploy to EC2 via SSH
        # if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "SSH connection successful!"

            if ! command -v aws &> /dev/null
            then
                echo "AWS CLI not found on EC2. Installing..."
                sudo apt-get update -y
                sudo apt-get install -y unzip
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip awscliv2.zip
                sudo ./aws/install
                rm -rf awscliv2.zip aws
                echo "AWS CLI installed."
            fi

            echo "Testing Docker Hub pull..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/luviraai-api:${{ github.sha }}

            echo "Testing AWS CLI and SSM access..."
            aws ssm get-parameters-by-path --path "/luviraai/prod" --recursive --query "Parameters[].[Name,Value]" --output text > /dev/null

            echo "All EC2 checks passed successfully!"

      - name: Remove Runner IP from AWS Security Group
        if: always()
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id 'sg-07be80aeabae4bf35' \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32 \
            --region ${{ secrets.AWS_REGION }}
